import { useLanguage } from "@/lib/i18n"; // Adjust path accordingly
import "@fontsource/nunito"; // Defaults to weight 400
import "@fontsource/nunito/400.css"; // Specify weight

const GenZInteriors: React.FC = () => {
  const { t } = useLanguage(); // Get the translation object based on the current language

  return (
    <>
      <div className="flex flex-col gap-6 text-gray-600 text-[12px] leading-relaxed p-5">
        <h3 className="text-xl md:text-5xl font-bold text-gray-800">
          {t.creatingTrendySpaces}
        </h3>
        <p>{t.introductionText1}</p>
        <p>{t.introductionText2}</p>

        <h3 className="text-xl font-bold text-gray-800">
          {t.understandingAestheticPreferences}
        </h3>
        <p>{t.aestheticPreferencesText}</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>{t.colorPalettes}</li>
          <p>{t.colorPalettesText}</p>
          <li>{t.eclecticFurnitureAndDecor}</li>
          <p>{t.eclecticFurnitureAndDecorText}</p>
          <li>{t.minimalistMeetsMaximalist}</li>
          <p>{t.minimalistMeetsMaximalistText}</p>
        </ul>

        <h3 className="text-xl font-bold text-gray-800">
          {t.keyElementsOfInstagramWorthyInterior}
        </h3>
        <p>{t.instagramWorthyDefinition}</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>{t.naturalLighting}</li>
          <p>{t.naturalLightingText}</p>
          <li>{t.accentWalls}</li>
          <p>{t.accentWallsText}</p>
          <li>{t.statementPieces}</li>
          <p>{t.statementPiecesText}</p>
          <li>{t.greeneryAndPlants}</li>
          <p>{t.greeneryAndPlantsText}</p>
          <li>{t.layeredTextures}</li>
          <p>{t.layeredTexturesText}</p>
          <li>{t.declutteredVisuals}</li>
          <p>{t.declutteredVisualsText}</p>
        </ul>

        <h3 className="text-xl font-bold text-gray-800">
          {t.incorporatingSustainabilityAndTechnology}
        </h3>
        <p>{t.sustainabilityTechText}</p>
        <h2 className="text-base font-bold text-gray-800">
          {t.sustainableMaterials}
        </h2>
        <p>{t.sustainableMaterialsText}</p>
        <h2 className="text-base font-bold text-gray-800">
          {t.smartHomeTechnology}
        </h2>
        <p>{t.smartHomeTechnologyText}</p>
        <h2 className="text-base font-bold text-gray-800">
          {t.multiFunctionalFurniture}
        </h2>
        <p>{t.multiFunctionalFurnitureText}</p>

        <h3 className="text-xl font-bold text-gray-800">
          {t.caseStudiesAndExamples}
        </h3>
        <p>{t.caseStudyIntro}</p>
        <ol className="list-decimal pl-6 space-y-3">
          <li>
            <strong>{t.economicEfficiency}</strong>
            <p>{t.economicEfficiencyText}</p>
          </li>
          <li>
            <strong>{t.geometricDreamBedroom}</strong>
            <p>{t.geometricDreamBedroomText}</p>
          </li>
          <li>
            <strong>{t.cafeInspiredKitchenNook}</strong>
            <p>{t.cafeInspiredKitchenNookText}</p>
          </li>
          <li>
            <strong>{t.bohoOutdoorBalcony}</strong>
            <p>{t.bohoOutdoorBalconyText}</p>
          </li>
        </ol>
      </div>

      <div className="max-w-5xl mx-auto px-4 mt-14 mb-14">
        <div className="rounded-lg max-h-[500px] overflow-hidden">
          <img
            decoding="async"
            loading="lazy"
            src="https://framerusercontent.com/images/PDGDvvv47n39NPYfptqokQ9sY.webp"
            alt="Generated by Styly"
            className="w-full h-[500px] object-cover object-center rounded-[inherit]"
            style={{ borderRadius: "inherit" }}
          />
        </div>
      </div>

      <div className="flex flex-col items-start space-y-4">
        <h2 className="text-2xl font-bold">{t.diyInstagramWorthyMakeovers}</h2>
        <p className="text-[12px] text-gray-800">{t.diyTipsIntro}</p>

        <ol className="list-decimal list-inside space-y-2 text-[12px] text-gray-800 mt-5">
          <li>
            <span className="font-semibold">{t.startWithMoodBoard}</span>
            <p className="my-5">{t.startWithMoodBoardText}</p>
          </li>

          <li>
            <span className="font-semibold">{t.maximizeWhatYouHave}</span>
            <p className="my-5">{t.maximizeWhatYouHaveText}</p>
          </li>

          <li>
            <span className="font-semibold">{t.getCreativeWithPaint}</span>
            <p className="my-5">{t.getCreativeWithPaintText}</p>
          </li>

          <li>
            <span className="font-semibold">{t.thriftForJewels}</span>
            <p className="my-5">{t.thriftForJewelsText}</p>
          </li>

          <li>
            <span className="font-semibold">{t.accessorizeThoughtfully}</span>
            <p className="my-5">{t.accessorizeThoughtfullyText}</p>
          </li>

          <li>
            <span className="font-semibold">{t.playWithAnglesForPhotos}</span>
            <p className="my-5">{t.playWithAnglesForPhotosText}</p>
          </li>
        </ol>
      </div>

      <div className="md:max-w-5xl mx-auto px-4 mt-14 mb-14">
        <div className="rounded-lg max-h-[500px] h-[550px] overflow-hidden">
          <img
            decoding="async"
            loading="lazy"
            src="https://framerusercontent.com/images/m0gVSPoNKygTbBepwSoUP6FHww.jpg"
            alt="Generated by Styly"
            className="w-full h-[500px] object-cover object-center rounded-[inherit]"
            style={{ borderRadius: "inherit" }}
          />
        </div>
      </div>

      <div className="flex flex-col items-start space-y-4 text-[12px] text-gray-800">
        <h2 className="text-2xl font-bold text-gray-700">
          {t.socialMediaShapingDesignTrends}
        </h2>
        <p>{t.socialMediaShapingDesignTrendsText}</p>

        <ul className="space-y-4 list-disc list-inside text-gray-800">
          <li>
            {t.crowdsourcingCreativity}
            <p className="my-5">{t.crowdsourcingCreativityText}</p>
          </li>
          <li>
            {t.massAppealToNicheInterests}
            <p className="my-5">{t.massAppealToNicheInterestsText}</p>
          </li>
          <li>
            <strong>{t.interactiveShopping}</strong>
            <p className="my-5">{t.interactiveShoppingText}</p>
          </li>
          <li>
            <strong>{t.empoweringNewCreators}</strong>
            <p className="my-5">{t.empoweringNewCreatorsText}</p>
          </li>
        </ul>

        <h2 className="text-2xl font-bold text-gray-700">{t.shareYourBestSpace}</h2>
        <p className="text-[12px] text-gray-700">{t.shareYourBestSpaceText}</p>
        <p className="text-[12px] text-gray-700">{t.shareYourBestSpaceInstagram}</p>
      </div>

      <div className="flex items-center justify-between mt-12">
        <div className="flex flex-col">
          <a
            href="./how-real-estate-agents-are-boosting-sales-with-ai-powered-virtual-staging-the-2025-market-reality"
            className="text-[12px] text-blue-400 hover:underline"
          >
            ‹ {t.prevArticle}
          </a>
        </div>

        <div className="flex flex-col text-right">
          <a
            href="./how-to-build-your-own-house-with-ai-tools-including-porch-design"
            className="text-[12px] text-blue-400 hover:underline"
          >
            {t.nextArticle} ›
          </a>
        </div>
      </div>
    </>
  );
};

export default GenZInteriors;
